USE MASTER
GO

IF EXISTS (SELECT * FROM sys.databases WHERE NAME = 'Zoo')
DROP DATABASE Zoo
GO

CREATE DATABASE Zoo
GO

USE Zoo
GO

CREATE TABLE TYPEANIMAL
(	NameType NVARCHAR(20) PRIMARY KEY,
	TypeID INT UNIQUE NOT NULL,
)
GO
CREATE TABLE ANIMAL(
	AnimalID INT PRIMARY KEY IDENTITY(1,1),
	TypeID INT NOT NULL,
	NameType NVARCHAR(20) NOT NULL,
	Age INT NOT NULL,
	Gender BIT NOT NULL,
	CONSTRAINT FK_Animal_Nametype FOREIGN KEY(NameType) REFERENCES TYPEANIMAL(NameType),
	CONSTRAINT FK_Animal_TypeID FOREIGN KEY(TypeID) REFERENCES TYPEANIMAL(TypeID)
)
GO

CREATE TABLE DISEASES
(	DiseasesID INT PRIMARY KEY,
	BeginTime DATETIME NOT NULL,
)
GO
CREATE TABLE KEPPER(
	KepperID INT PRIMARY KEY IDENTITY(1,1),
	KepperName NVARCHAR(20) NOT NULL,
	SSN INT NOT NULL,
	Address NVARCHAR(20) NOT NULL,
	PhoneNumber VARCHAR(10) NOT NULL,
	)
GO
CREATE TABLE Kep_Dies
(	KepperID INT PRIMARY KEY IDENTITY(1,1),
	DiseasesID INT,
	CONSTRAINT FK_Kep_Dies_DISEASES FOREIGN KEY(DiseasesID) REFERENCES DISEASES(DiseasesID),
	CONSTRAINT FK_Kep_Dies_KEPPER FOREIGN KEY(KepperID) REFERENCES KEPPER(KepperID)
	)
GO
ALTER TABLE ANIMAL ADD KepperID INT NOT NULL CONSTRAINT FK_ANIMAL_KEPPER FOREIGN KEY(KepperID) REFERENCES KEPPER(KepperID)

CREATE TABLE CAGES(
	CagesID INT PRIMARY KEY IDENTITY(1,1),
	Quantity Int NOT NULL,
	Height FLOAT NOT NULL,
)
GO
CREATE TABLE KEPPERCAGES(
	KepperCageID INT PRIMARY KEY IDENTITY(1,1),
	KepperCageName NVARCHAR(20) NOT NULL,
	SSN INT NOT NULL,
	Address NVARCHAR(20) NOT NULL,
	PhoneNumber VARCHAR(10) NOT NULL,
	)
GO
CREATE TABLE CAGES_ANIMAL(
	CagesID INT,
	AnimalID INT,
	PRIMARY KEY(CagesID,AnimalID),
	KepperCageID INT NOT NULL,
	CONSTRAINT FK_CAGES_KEEP_CAGES FOREIGN KEY(CagesID) REFERENCES CAGES(CagesID),
	CONSTRAINT FK_CAGES_KEEP_KEPPERCAGES FOREIGN KEY(KepperCageID) REFERENCES KEPPERCAGES(KepperCageID),
	CONSTRAINT FK_CAGES_KEEP_ANIMAL FOREIGN KEY(AnimalID) REFERENCES ANIMAL(AnimalID)
)
GO
ALTER TABLE ANIMAL ADD CagesID INT NOT NULL CONSTRAINT FK_ANIMAL_CAGES FOREIGN KEY(CagesID) REFERENCES CAGES(CagesID)
